version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: off_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: off_datamart
    ports:
      - "3309:3306"
    volumes:
      - ./sql/dll.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql

volumes:
  db_data: